In [3]:
import cosmofast as cf
import numpy as np
foo = np.load('cosmofast/planck_18/data/commander.npz')
test = np.load("cosmofast/tests/test_commander.npz")
foo = np.load('cosmofast/planck_18/data/commander.npz')
test = np.load("cosmofast/tests/test_commander.npz")

In [4]:
cl2x = foo['cl2x']
mu = foo['mu']
cov = foo['cov']
cov_inv = np.linalg.inv(cov)
offset = foo['offset']

In [6]:
test_f = np.empty(1)
cf.planck_18._commander._commander_f(
    test['test_param'][2:30], test['test_param'][30], test_f, cl2x, mu, cov_inv)
test_f - offset, test['test_value']

(array([-11.5889457]), array([-11.58894468]))

In [8]:
test_j = np.empty((1, 29))
cf.planck_18._commander._commander_j(
    test['test_param'][2:30], test['test_param'][30], test_j, cl2x, mu, cov_inv)
test_j

array([[-1.82601744e-03, -2.15338306e-04, -3.72038578e-03,
         2.11431073e-02, -1.64171869e-02,  2.83200456e-02,
        -2.86416040e-02, -2.10838882e-02, -1.58604467e-03,
         1.93121620e-02, -2.58853990e-02, -1.14568505e-01,
        -1.98857368e-02,  1.29311302e-01, -1.97595189e-01,
         1.61822208e-01, -2.34213521e-01,  7.17711206e-02,
        -3.53727698e-01, -4.84020132e-01, -6.03975529e-01,
        -3.63066927e-01, -2.30973671e-01, -4.36055769e-01,
        -3.92852847e-01, -3.41070415e-02,  3.88183675e-01,
        -1.29018264e-01,  7.32470011e+01]])

In [10]:
test_fjf = np.empty(1)
test_fjj = np.empty((1, 29))
cf.planck_18._commander._commander_fj(
    test['test_param'][2:30], test['test_param'][30], test_fjf, test_fjj, cl2x,
    mu, cov_inv)
test_fjf - offset, test_fjj

(array([-11.5889457]),
 array([[-1.82601744e-03, -2.15338306e-04, -3.72038578e-03,
          2.11431073e-02, -1.64171869e-02,  2.83200456e-02,
         -2.86416040e-02, -2.10838882e-02, -1.58604467e-03,
          1.93121620e-02, -2.58853990e-02, -1.14568505e-01,
         -1.98857368e-02,  1.29311302e-01, -1.97595189e-01,
          1.61822208e-01, -2.34213521e-01,  7.17711206e-02,
         -3.53727698e-01, -4.84020132e-01, -6.03975529e-01,
         -3.63066927e-01, -2.30973671e-01, -4.36055769e-01,
         -3.92852847e-01, -3.41070415e-02,  3.88183675e-01,
         -1.29018264e-01,  7.32470011e+01]]))

In [12]:
import numdifftools as nd

def bf_f(x):
    test_f = np.empty(1)
    cf.planck_18._commander._commander_f(
        x[:-1], x[-1], test_f, cl2x, mu, cov_inv)
    return test_f - offset

def bf_j(x):
    test_j = np.empty((1, 29))
    cf.planck_18._commander._commander_j(
        x[:-1], x[-1], test_j, cl2x, mu, cov_inv)
    return test_j

bf_f(test['test_param'][2:]), bf_j(test['test_param'][2:])

(array([-11.5889457]),
 array([[-1.82601744e-03, -2.15338306e-04, -3.72038578e-03,
          2.11431073e-02, -1.64171869e-02,  2.83200456e-02,
         -2.86416040e-02, -2.10838882e-02, -1.58604467e-03,
          1.93121620e-02, -2.58853990e-02, -1.14568505e-01,
         -1.98857368e-02,  1.29311302e-01, -1.97595189e-01,
          1.61822208e-01, -2.34213521e-01,  7.17711206e-02,
         -3.53727698e-01, -4.84020132e-01, -6.03975529e-01,
         -3.63066927e-01, -2.30973671e-01, -4.36055769e-01,
         -3.92852847e-01, -3.41070415e-02,  3.88183675e-01,
         -1.29018264e-01,  7.32470011e+01]]))

In [15]:
nd.Gradient(bf_f, step=1e-8)(test['test_param'][2:])

array([-1.82609484e-03, -2.14583908e-04, -3.72040179e-03,  2.11429098e-02,
       -1.64178006e-02,  2.83193914e-02, -2.86405568e-02, -2.10846453e-02,
       -1.58593140e-03,  1.93125517e-02, -2.58850720e-02, -1.14569332e-01,
       -1.98852491e-02,  1.29311673e-01, -1.97596252e-01,  1.61821846e-01,
       -2.34213361e-01,  7.17705011e-02, -3.53728071e-01, -4.84018872e-01,
       -6.03975540e-01, -3.63067445e-01, -2.30973286e-01, -4.36055816e-01,
       -3.92853397e-01, -3.41060515e-02,  3.88185131e-01, -1.29018930e-01,
        7.32470004e+01])