In [1]:
import cosmofast as cf
import numpy as np
f_ee = np.load('cosmofast/planck_18/data/simall_ee.npz')
f_bb = np.load('cosmofast/planck_18/data/simall_bb.npz')
test_ee = np.load("cosmofast/tests/test_simall_ee.npz")
test_bb = np.load("cosmofast/tests/test_simall_bb.npz")

In [8]:
test_f = np.empty(1)
cf.planck_18._simall._simall_f(
    test_ee['test_param'][2:30], test_ee['test_param'][30], test_f,
    f_ee['c'], f_ee['step'], f_ee['n_step'])
test_f, test_ee['test_value'] # array([-198.02824807])

(array([-198.02824807]), array([-197.99117722]))

In [11]:
test_j = np.empty((1, 29))
cf.planck_18._simall._simall_j(
    test_ee['test_param'][2:30], test_ee['test_param'][30], test_j,
    f_ee['c'], f_ee['step'], f_ee['n_step'])
test_j

array([[ 1.31796926e+01,  1.16615595e+01, -1.03902301e+02,
         4.01998444e+02, -1.50388250e+02, -7.59025089e+02,
         4.63314398e+01, -9.02993312e+02, -9.36962965e+02,
        -1.06925098e+03, -2.36290951e+03, -2.77996355e+03,
        -3.05817224e+03, -2.08293166e+03, -9.17772695e+02,
         1.06187472e+03,  7.93088103e+01, -4.09399041e+03,
        -4.85379626e+03,  3.30355791e+03, -3.03019778e+03,
         4.87852324e+03,  3.43231436e+03,  1.71966868e+03,
        -5.09218424e+03,  6.20992306e+03,  2.84223800e+02,
        -6.17544881e+03,  2.03457697e+00]])

In [12]:
test_fjf = np.empty(1)
test_fjj = np.empty((1, 29))
cf.planck_18._simall._simall_fj(
    test_ee['test_param'][2:30], test_ee['test_param'][30], test_fjf, test_fjj,
    f_ee['c'], f_ee['step'], f_ee['n_step'])
test_fjf, test_fjj

(array([-198.02824807]),
 array([[ 1.31796926e+01,  1.16615595e+01, -1.03902301e+02,
          4.01998444e+02, -1.50388250e+02, -7.59025089e+02,
          4.63314398e+01, -9.02993312e+02, -9.36962965e+02,
         -1.06925098e+03, -2.36290951e+03, -2.77996355e+03,
         -3.05817224e+03, -2.08293166e+03, -9.17772695e+02,
          1.06187472e+03,  7.93088103e+01, -4.09399041e+03,
         -4.85379626e+03,  3.30355791e+03, -3.03019778e+03,
          4.87852324e+03,  3.43231436e+03,  1.71966868e+03,
         -5.09218424e+03,  6.20992306e+03,  2.84223800e+02,
         -6.17544881e+03,  2.03457697e+00]]))

In [13]:
import numdifftools as nd

def bf_f(x):
    test_f = np.empty(1)
    cf.planck_18._simall._simall_f(
        x[:-1], x[-1], test_f,
        f_ee['c'], f_ee['step'], f_ee['n_step'])
    return test_f

def bf_j(x):
    test_j = np.empty((1, 29))
    cf.planck_18._simall._simall_j(
        x[:-1], x[-1], test_j,
        f_ee['c'], f_ee['step'], f_ee['n_step'])
    return test_j

bf_f(test_ee['test_param'][2:]), bf_j(test_ee['test_param'][2:])

(array([-198.02824807]),
 array([[ 1.31796926e+01,  1.16615595e+01, -1.03902301e+02,
          4.01998444e+02, -1.50388250e+02, -7.59025089e+02,
          4.63314398e+01, -9.02993312e+02, -9.36962965e+02,
         -1.06925098e+03, -2.36290951e+03, -2.77996355e+03,
         -3.05817224e+03, -2.08293166e+03, -9.17772695e+02,
          1.06187472e+03,  7.93088103e+01, -4.09399041e+03,
         -4.85379626e+03,  3.30355791e+03, -3.03019778e+03,
          4.87852324e+03,  3.43231436e+03,  1.71966868e+03,
         -5.09218424e+03,  6.20992306e+03,  2.84223800e+02,
         -6.17544881e+03,  2.03457697e+00]]))

In [20]:
nd.Gradient(bf_f, step=1e-8)(test_ee['test_param'][2:])

array([ 1.31796924e+01,  1.16615596e+01, -1.03902301e+02,  4.01998444e+02,
       -1.50388251e+02, -7.59025089e+02,  4.63314396e+01, -9.02993312e+02,
       -9.36962965e+02, -1.06925098e+03, -2.36290951e+03, -2.77996355e+03,
       -3.05817224e+03, -2.08293166e+03, -9.17772695e+02,  1.06187473e+03,
        7.93088096e+01, -4.09399041e+03, -4.85379627e+03,  3.30355791e+03,
       -3.03019778e+03,  4.87852324e+03,  3.43231436e+03,  1.71966869e+03,
       -5.09218424e+03,  6.20992306e+03,  2.84223801e+02, -6.17544881e+03,
        2.03457945e+00])

In [21]:
import cosmofast as cf
import numpy as np
f_ee = np.load('cosmofast/planck_18/data/simall_ee.npz')
f_bb = np.load('cosmofast/planck_18/data/simall_bb.npz')
test_ee = np.load("cosmofast/tests/test_simall_ee.npz")
test_bb = np.load("cosmofast/tests/test_simall_bb.npz")

In [22]:
test_f = np.empty(1)
cf.planck_18._simall._simall_f(
    test_bb['test_param'][2:30], test_bb['test_param'][30], test_f,
    f_bb['c'], f_bb['step'], f_bb['n_step'])
test_f, test_bb['test_value'] # array([-194.9979613])

(array([-194.9979613]), array([-194.95735006]))

In [23]:
test_j = np.empty((1, 29))
cf.planck_18._simall._simall_j(
    test_bb['test_param'][2:30], test_bb['test_param'][30], test_j,
    f_bb['c'], f_bb['step'], f_bb['n_step'])
test_j

array([[-6.79503438e+01,  2.09263183e+01, -2.39422060e+01,
        -2.71523277e+02, -9.92971952e+02, -2.94953790e+02,
        -1.66798287e+03, -1.02598167e+03,  6.35567252e+02,
        -3.92816833e+03,  6.95641948e+02,  4.11494748e+03,
        -3.80149539e+03, -3.75578232e+03, -4.88208951e+03,
         2.11964880e+03, -3.30358464e+02, -3.22399700e+03,
         1.73435785e+03,  3.35100840e+03, -7.59027134e+03,
        -5.39496003e+03,  1.45779284e+04, -2.62784484e+03,
         7.93245109e+03, -5.58269184e+03, -6.62479456e+03,
         2.97190287e+02,  6.04487001e-01]])

In [24]:
test_fjf = np.empty(1)
test_fjj = np.empty((1, 29))
cf.planck_18._simall._simall_fj(
    test_bb['test_param'][2:30], test_bb['test_param'][30], test_fjf, test_fjj,
    f_bb['c'], f_bb['step'], f_bb['n_step'])
test_fjf, test_fjj

(array([-194.9979613]),
 array([[-6.79503438e+01,  2.09263183e+01, -2.39422060e+01,
         -2.71523277e+02, -9.92971952e+02, -2.94953790e+02,
         -1.66798287e+03, -1.02598167e+03,  6.35567252e+02,
         -3.92816833e+03,  6.95641948e+02,  4.11494748e+03,
         -3.80149539e+03, -3.75578232e+03, -4.88208951e+03,
          2.11964880e+03, -3.30358464e+02, -3.22399700e+03,
          1.73435785e+03,  3.35100840e+03, -7.59027134e+03,
         -5.39496003e+03,  1.45779284e+04, -2.62784484e+03,
          7.93245109e+03, -5.58269184e+03, -6.62479456e+03,
          2.97190287e+02,  6.04487001e-01]]))

In [25]:
import numdifftools as nd

def bf_f(x):
    test_f = np.empty(1)
    cf.planck_18._simall._simall_f(
        x[:-1], x[-1], test_f,
        f_bb['c'], f_bb['step'], f_bb['n_step'])
    return test_f

def bf_j(x):
    test_j = np.empty((1, 29))
    cf.planck_18._simall._simall_j(
        x[:-1], x[-1], test_j,
        f_bb['c'], f_bb['step'], f_bb['n_step'])
    return test_j

bf_f(test_bb['test_param'][2:]), bf_j(test_bb['test_param'][2:])

(array([-194.9979613]),
 array([[-6.79503438e+01,  2.09263183e+01, -2.39422060e+01,
         -2.71523277e+02, -9.92971952e+02, -2.94953790e+02,
         -1.66798287e+03, -1.02598167e+03,  6.35567252e+02,
         -3.92816833e+03,  6.95641948e+02,  4.11494748e+03,
         -3.80149539e+03, -3.75578232e+03, -4.88208951e+03,
          2.11964880e+03, -3.30358464e+02, -3.22399700e+03,
          1.73435785e+03,  3.35100840e+03, -7.59027134e+03,
         -5.39496003e+03,  1.45779284e+04, -2.62784484e+03,
          7.93245109e+03, -5.58269184e+03, -6.62479456e+03,
          2.97190287e+02,  6.04487001e-01]]))

In [26]:
nd.Gradient(bf_f, step=1e-8)(test_bb['test_param'][2:])

array([-6.79503434e+01,  2.09263193e+01, -2.39422052e+01, -2.71523277e+02,
       -9.92971951e+02, -2.94953790e+02, -1.66798287e+03, -1.02598167e+03,
        6.35567252e+02, -3.92816833e+03,  6.95641948e+02,  4.11494748e+03,
       -3.80149539e+03, -3.75578233e+03, -4.88208952e+03,  2.11964881e+03,
       -3.30358458e+02, -3.22399700e+03,  1.73435785e+03,  3.35100842e+03,
       -7.59027130e+03, -5.39496004e+03,  1.45779285e+04, -2.62784477e+03,
        7.93245120e+03, -5.58269182e+03, -6.62479447e+03,  2.97190055e+02,
        6.04482867e-01])