In [1]:
import cosmofast as cf
from astropy.io import fits
import numpy as np
bins = fits.open('cosmofast/planck_18/data/legacy-smica/bins')
cor0 = fits.open('cosmofast/planck_18/data/legacy-smica/cor0')
cors = fits.open('cosmofast/planck_18/data/legacy-smica/cors')
pp_hat = fits.open('cosmofast/planck_18/data/legacy-smica/pp_hat')
siginv = fits.open('cosmofast/planck_18/data/legacy-smica/siginv')

In [2]:
bins.info()

Filename: cosmofast/planck_18/data/legacy-smica/bins
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (22509,)   float64   


In [3]:
cor0.info()

Filename: cosmofast/planck_18/data/legacy-smica/cor0
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (9,)   float64   


In [4]:
cors.info()

Filename: cosmofast/planck_18/data/legacy-smica/cors
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (90036,)   float64   


In [5]:
pp_hat.info()

Filename: cosmofast/planck_18/data/legacy-smica/pp_hat
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (9,)   float64   


In [6]:
siginv.info()

Filename: cosmofast/planck_18/data/legacy-smica/siginv
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (81,)   float64   


In [7]:
F = np.zeros((9, 2501 * 4))
F[:, :2501] += bins[0].data.reshape((9, 2501)) * (
    np.arange(2501) * np.arange(2501) * np.arange(1, 2502) * np.arange(1, 2502)
    / 2 / np.pi)[np.newaxis]
F += cors[0].data.reshape((9, 10004)) * np.concatenate((
    np.arange(2501) * np.arange(2501) * np.arange(1, 2502) * np.arange(1, 2502)
    / 2 / np.pi,
    np.arange(2501) * np.arange(1, 2502) / 2 / np.pi,
    np.arange(2501) * np.arange(1, 2502) / 2 / np.pi,
    np.arange(2501) * np.arange(1, 2502) / 2 / np.pi,))[np.newaxis]
mu = cor0[0].data + pp_hat[0].data

In [8]:
test_s = np.load("cosmofast/tests/test_smica.npz")

In [10]:
# lensing, TT, EE, TE
test = np.empty(1)
cf.planck_18._smica._smica_f(
    test_s['test_param'][:-1], test_s['test_param'][-1], test,
    F,
    mu,
    siginv[0].data.byteswap().newbyteorder().reshape((9, 9)), 3, 2, 2500, 9)
test, test_s['test_value']

(array([-4.41526344]), array([-4.41526344]))

In [11]:
np.savez_compressed(
    'cosmofast/planck_18/data/smica.npz', F=F, mu=mu,
    siginv = siginv[0].data.byteswap().newbyteorder().reshape((9, 9)),
    n_cmb=3, l_min=2, l_max=2500, n_bin=9)

In [1]:
import cosmofast as cf
import numpy as np
f_smica = np.load('cosmofast/planck_18/data/smica.npz')
test_smica = np.load("cosmofast/tests/test_smica.npz")

In [2]:
# lensing, TT, EE, TE
test = np.empty(1)
cf.planck_18._smica._smica_f(
    test_smica['test_param'][:-1], test_smica['test_param'][-1], test,
    f_smica['F'],
    f_smica['mu'],
    f_smica['siginv'], f_smica['n_cmb'], f_smica['l_min'],
    f_smica['l_max'], f_smica['n_bin'])
test, test_smica['test_value']

(array([-4.41526344]), array([-4.41526344]))

In [1]:
import cosmofast as cf
from astropy.io import fits
import numpy as np
bins = fits.open('cosmofast/planck_18/data/legacy-smica-cmb-marged/bins')
cor0 = fits.open('cosmofast/planck_18/data/legacy-smica-cmb-marged/cor0')
cors = fits.open('cosmofast/planck_18/data/legacy-smica-cmb-marged/cors')
pp_hat = fits.open('cosmofast/planck_18/data/legacy-smica-cmb-marged/pp_hat')
siginv = fits.open('cosmofast/planck_18/data/legacy-smica-cmb-marged/siginv')

In [2]:
bins.info()

Filename: cosmofast/planck_18/data/legacy-smica-cmb-marged/bins
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (22509,)   float64   


In [3]:
cor0.info()

Filename: cosmofast/planck_18/data/legacy-smica-cmb-marged/cor0
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (9,)   float64   


In [4]:
cors.info()

Filename: cosmofast/planck_18/data/legacy-smica-cmb-marged/cors
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (22509,)   float64   


In [5]:
pp_hat.info()

Filename: cosmofast/planck_18/data/legacy-smica-cmb-marged/pp_hat
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (9,)   float64   


In [6]:
siginv.info()

Filename: cosmofast/planck_18/data/legacy-smica-cmb-marged/siginv
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       5   (81,)   float64   


In [7]:
F = np.zeros((9, 2501))
F += bins[0].data.reshape((9, 2501)) * (
    np.arange(2501) * np.arange(2501) * np.arange(1, 2502) * np.arange(1, 2502)
    / 2 / np.pi)[np.newaxis]
mu = cor0[0].data + pp_hat[0].data

In [8]:
test_scm = np.load("cosmofast/tests/test_smica_cmb_marged.npz")

In [9]:
# lensing
test = np.empty(1)
cf.planck_18._smica._smica_f(
    test_scm['test_param'][:-1], test_scm['test_param'][-1], test,
    F,
    mu,
    siginv[0].data.byteswap().newbyteorder().reshape((9, 9)), 0, 2, 2500, 9)
test, test_scm['test_value']

(array([-8.23033182]), array([-8.23033182]))

In [10]:
np.savez_compressed(
    'cosmofast/planck_18/data/smica_cmb_marged.npz', F=F, mu=mu,
    siginv = siginv[0].data.byteswap().newbyteorder().reshape((9, 9)),
    n_cmb=0, l_min=2, l_max=2500, n_bin=9)

In [1]:
import cosmofast as cf
import numpy as np
f_smica = np.load('cosmofast/planck_18/data/smica_cmb_marged.npz')
test_smica = np.load("cosmofast/tests/test_smica_cmb_marged.npz")

In [2]:
# lensing
test = np.empty(1)
cf.planck_18._smica._smica_f(
    test_smica['test_param'][:-1], test_smica['test_param'][-1], test,
    f_smica['F'],
    f_smica['mu'],
    f_smica['siginv'], f_smica['n_cmb'], f_smica['l_min'],
    f_smica['l_max'], f_smica['n_bin'])
test, test_smica['test_value']

(array([-8.23033182]), array([-8.23033182]))