In [2]:
import cosmofast as cf
import numpy as np
f_smica = np.load('cosmofast/planck_18/data/smica.npz')
test_smica = np.load("cosmofast/tests/test_smica.npz")

In [3]:
# lensing, TT, EE, TE
test_f = np.empty(1)
lens_b = np.empty(f_smica['n_bin'])
cmb_b = np.empty(f_smica['n_bin'])
cf.planck_18._smica._get_binned_cls(
    test_smica['test_param'][:-1], lens_b, cmb_b, f_smica['F'],
    f_smica['n_cmb'], f_smica['l_min'], f_smica['l_max'], f_smica['n_bin'])
cf.planck_18._smica._smica_f(
    lens_b, cmb_b, test_smica['test_param'][-1], test_f, f_smica['mu'],
    f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
test_f, test_smica['test_value']

(array([-4.41526344]), array([-4.41526344]))

In [4]:
# lensing, TT, EE, TE
test_j = np.empty((1, (2 * f_smica['n_bin'] + 1)))
lens_b = np.empty(f_smica['n_bin'])
cmb_b = np.empty(f_smica['n_bin'])
cf.planck_18._smica._get_binned_cls(
    test_smica['test_param'][:-1], lens_b, cmb_b, f_smica['F'],
    f_smica['n_cmb'], f_smica['l_min'], f_smica['l_max'], f_smica['n_bin'])
cf.planck_18._smica._smica_j(
    lens_b, cmb_b, test_smica['test_param'][-1], test_j, f_smica['mu'],
    f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
test_j

array([[ 3.52313784e+07,  1.17281701e+08,  6.82370984e+07,
        -1.91295159e+08, -3.05372104e+08, -2.84785643e+08,
         2.38260934e+08,  3.21848841e+08, -1.86966026e+08,
         3.51610212e+07,  1.17047489e+08,  6.81008286e+07,
        -1.90913142e+08, -3.04762275e+08, -2.84216925e+08,
         2.37785126e+08,  3.21206108e+08, -1.86592654e+08,
         1.85691280e+01]])

In [5]:
# lensing, TT, EE, TE
test_fjf = np.empty(1)
test_fjj = np.empty((1, (2 * f_smica['n_bin'] + 1)))
lens_b = np.empty(f_smica['n_bin'])
cmb_b = np.empty(f_smica['n_bin'])
cf.planck_18._smica._get_binned_cls(
    test_smica['test_param'][:-1], lens_b, cmb_b, f_smica['F'],
    f_smica['n_cmb'], f_smica['l_min'], f_smica['l_max'], f_smica['n_bin'])
cf.planck_18._smica._smica_fj(
    lens_b, cmb_b, test_smica['test_param'][-1], test_fjf, test_fjj, f_smica['mu'],
    f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
test_fjf, test_fjj

(array([-4.41526344]),
 array([[ 3.52313784e+07,  1.17281701e+08,  6.82370984e+07,
         -1.91295159e+08, -3.05372104e+08, -2.84785643e+08,
          2.38260934e+08,  3.21848841e+08, -1.86966026e+08,
          3.51610212e+07,  1.17047489e+08,  6.81008286e+07,
         -1.90913142e+08, -3.04762275e+08, -2.84216925e+08,
          2.37785126e+08,  3.21206108e+08, -1.86592654e+08,
          1.85691280e+01]]))

In [6]:
import numdifftools as nd

xx = np.concatenate((lens_b, cmb_b, test_smica['test_param'][-1:]))

def bf_f(x):
    test_f = np.empty(1)
    cf.planck_18._smica._smica_f(
        x[:f_smica['n_bin']], x[f_smica['n_bin']:(2 * f_smica['n_bin'])],
        x[-1], test_f, f_smica['mu'],
        f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
    return test_f

def bf_j(x):
    test_j = np.empty((1, (2 * f_smica['n_bin'] + 1)))
    cf.planck_18._smica._smica_j(
        x[:f_smica['n_bin']], x[f_smica['n_bin']:(2 * f_smica['n_bin'])],
        x[-1], test_j, f_smica['mu'],
        f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
    return test_j

bf_f(xx), bf_j(xx)

(array([-4.41526344]),
 array([[ 3.52313784e+07,  1.17281701e+08,  6.82370984e+07,
         -1.91295159e+08, -3.05372104e+08, -2.84785643e+08,
          2.38260934e+08,  3.21848841e+08, -1.86966026e+08,
          3.51610212e+07,  1.17047489e+08,  6.81008286e+07,
         -1.90913142e+08, -3.04762275e+08, -2.84216925e+08,
          2.37785126e+08,  3.21206108e+08, -1.86592654e+08,
          1.85691280e+01]]))

In [8]:
nd.Gradient(bf_f, step=1e-8)(xx)

array([ 3.52313784e+07,  1.17281701e+08,  6.82370984e+07, -1.91295159e+08,
       -3.05372104e+08, -2.84785643e+08,  2.38260934e+08,  3.21848841e+08,
       -1.86966026e+08,  3.51610212e+07,  1.17047489e+08,  6.81008286e+07,
       -1.90913142e+08, -3.04762275e+08, -2.84216925e+08,  2.37785126e+08,
        3.21206108e+08, -1.86592654e+08,  1.85691287e+01])

In [9]:
import cosmofast as cf
import numpy as np
f_smica = np.load('cosmofast/planck_18/data/smica_cmb_marged.npz')
test_smica = np.load("cosmofast/tests/test_smica_cmb_marged.npz")

In [10]:
# lensing
test_f = np.empty(1)
lens_b = np.empty(f_smica['n_bin'])
cmb_b = np.empty(1)
cf.planck_18._smica._get_binned_cls(
    test_smica['test_param'][:-1], lens_b, cmb_b, f_smica['F'],
    f_smica['n_cmb'], f_smica['l_min'], f_smica['l_max'], f_smica['n_bin'])
cf.planck_18._smica._smica_f(
    lens_b, cmb_b, 1., test_f, f_smica['mu'],
    f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
test_f, test_smica['test_value']

(array([-8.23033182]), array([-8.23033182]))

In [11]:
# lensing
test_j = np.empty((1, f_smica['n_bin']))
lens_b = np.empty(f_smica['n_bin'])
cmb_b = np.empty(1)
cf.planck_18._smica._get_binned_cls(
    test_smica['test_param'][:-1], lens_b, cmb_b, f_smica['F'],
    f_smica['n_cmb'], f_smica['l_min'], f_smica['l_max'], f_smica['n_bin'])
cf.planck_18._smica._smica_j(
    lens_b, cmb_b, 1., test_j, f_smica['mu'],
    f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
test_j

array([[ 4.23909602e+07,  1.97241860e+08,  2.15426993e+08,
        -9.47288006e+07, -1.31962383e+08, -1.62344785e+08,
         4.67238433e+08,  5.88548103e+08,  1.15188023e+08]])

In [12]:
# lensing
test_fjf = np.empty(1)
test_fjj = np.empty((1, f_smica['n_bin']))
lens_b = np.empty(f_smica['n_bin'])
cmb_b = np.empty(1)
cf.planck_18._smica._get_binned_cls(
    test_smica['test_param'][:-1], lens_b, cmb_b, f_smica['F'],
    f_smica['n_cmb'], f_smica['l_min'], f_smica['l_max'], f_smica['n_bin'])
cf.planck_18._smica._smica_fj(
    lens_b, cmb_b, 1., test_fjf, test_fjj, f_smica['mu'],
    f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
test_fjf, test_fjj

(array([-8.23033182]),
 array([[ 4.23909602e+07,  1.97241860e+08,  2.15426993e+08,
         -9.47288006e+07, -1.31962383e+08, -1.62344785e+08,
          4.67238433e+08,  5.88548103e+08,  1.15188023e+08]]))

In [13]:
import numdifftools as nd

def bf_f(x):
    test_f = np.empty(1)
    cf.planck_18._smica._smica_f(
        x, cmb_b, 1., test_f, f_smica['mu'],
        f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
    return test_f

def bf_j(x):
    test_j = np.empty((1, f_smica['n_bin']))
    cf.planck_18._smica._smica_j(
        x, cmb_b, 1., test_j, f_smica['mu'],
        f_smica['siginv'], f_smica['n_cmb'], f_smica['n_bin'])
    return test_j

bf_f(lens_b), bf_j(lens_b)

(array([-8.23033182]),
 array([[ 4.23909602e+07,  1.97241860e+08,  2.15426993e+08,
         -9.47288006e+07, -1.31962383e+08, -1.62344785e+08,
          4.67238433e+08,  5.88548103e+08,  1.15188023e+08]]))

In [14]:
nd.Gradient(bf_f, step=1e-8)(lens_b)

array([ 4.23909602e+07,  1.97241860e+08,  2.15426993e+08, -9.47288006e+07,
       -1.31962383e+08, -1.62344785e+08,  4.67238433e+08,  5.88548103e+08,
        1.15188023e+08])